### PR TITLE
Fullscreen mode (Maximaze)

### PR DESCRIPTION
**Pull request by plugtopus**
**before**
3ze7xxq

**after** 
182e8-clip-1425kb

### CODE REVIEW

**Comment by plugtopus** [comment]
Next time I will add to config file

**Comment by andreakarasho** [comment]
Can you use CamelCase pattern :D?

**Comment by plugtopus** [comment]
Oh yes, sorry :)

**Comment by andreakarasho** [comment]
Oh i see that you are on master branch.
That branch is outdated (soon it ll be updated), point this fix to the dev branch instead

**Comment by plugtopus** [comment]
right?
3zed6s2

**Pull request merged**
