### PR TITLE
IsFixedTimeStep param to settings.json (fast AMD fix)

### PR DESCRIPTION
**Pull request by plugtopus**
CPU Type
Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz

Graphics Chipset
AMD Radeon R9 200 Series

Memory Size
4096 MB

System Memory
32 GB

Windows Version
Windows 10 (64 bit)

===

**### fixedtimestep = true**

fps 20-40

3zfanro

**### fixedtimestep = false**

3zfabtq

fps 50-60

===

3zgjj9m

default value I did not change (**IsFixedTimeStep = true;**)

### CODE REVIEW

**Comment by plugtopus** [comment]
### ty KaRaShO' !!

**Comment by andreakarasho** [comment]
I have to do a deep research about it before merge

**Comment by plugtopus** [comment]
More info http://rbwhitaker.wikidot.com/time-steps

I think it is good "fast fix" AMD problem because in some places (big cities) I get 10-20 fps. The option is added to the settings and disabled by default, it does not break work for other users. I think FixedTimeStep bad idea in dynamic render game.

**Comment by plugtopus** [comment]
I am ready for any testing if you have a better idea how to fix it.

**Comment by plugtopus** [comment]
**dev branch**

### 28-40 fps
"GameWindowPosition": "-5,-5",
"GameWindowSize": "1536,897",
**IsFixedTimeStep = false;**
TargetElapsedTime = TimeSpan.FromSeconds(1.0f / MAX_FPS);



### 45-58 fps
"GameWindowPosition": "-5,-5",
"GameWindowSize": "1536,897",
**IsFixedTimeStep = true;**

**Pull request merged**
