### PR TITLE
Added borderless window mode

### PR DESCRIPTION
**Pull request by paezao**
Added Borderless Window functionality.

### CODE REVIEW

**Comment by andreakarasho** [comment]
What is the behaviour if you switch scene [login -> game, game -> login]

**Comment by paezao** [comment]
It stays borderless. Do you want it to be always bordered in the login scene?

**Comment by andreakarasho** [comment]
the correct behaviour is: stays in bordless when you are in game only

**Comment by paezao** [comment]
Okay @andreakarasho, it's done. Login scene is now always bordered.

**Comment by andreakarasho** [comment]
Reviewing....

**Pull request merged**
