### PR TITLE
fix ScrollArea

### PR DESCRIPTION
**Pull request by plugtopus**
[fix 9d50234e99530c0feca43df6efe1b4e9f81237ee](https://github.com/andreakarasho/ClassicUO/commit/9d50234e99530c0feca43df6efe1b4e9f81237ee)

3zokk3h

3zokix1

### CODE REVIEW

**Comment by andreakarasho** [comment]
and at bottom ?

**Comment by plugtopus** [comment]
:( moment please :)

**Comment by plugtopus** [comment]
1 fix = new 2 bugs 🥇 xD

**Comment by plugtopus** [comment]
3zooisn

3zook9t

**Comment by andreakarasho** [comment]
nice! i'll merge soon

**Pull request merged**
