### PR TITLE
GameScreen() Death Mode + Death Screen xD

### PR DESCRIPTION
**Pull request by zolter**
https://i.imgur.com/30Px1r5.gif

e86d0-clip-757kb 1

044e7-clip-5kb 1

### CODE REVIEW

**Comment by andreakarasho** [comment]
Can you add an options to disable it?

**Comment by zolter** [comment]
Yep, 5 min

**Comment by zolter** [comment]
Done, I add:

1. **Enable Death Screen** _(window that says "You are dead.")_
2. **Black&White mode for dead player**

**Comment by andreakarasho** [comment]
very nice! thanks

**Pull request merged**
