### PR TITLE
Option to hue container gumps by the item hue

### PR DESCRIPTION
**Pull request by roxya**
image

### CODE REVIEW

**Comment by andreakarasho** [comment]
I wonder if i'ts worth making this as a default feature. What do you think about?

**Comment by roxya** [comment]
It's very nice for containers you have control over. Good enough to be the default for new profiles in my opinion.

People may find it annoying if friends/guild houses choose ugly colours. And there are people who customise their container gump art. But as long as it can be disabled it should be fine.

Let me know if you want me to update the PR with it as a default setting.

**Comment by andreakarasho** [comment]
I think we can set it enabled by default.
Also there are conflicts with `ResGumps.resx` file. Probably due to the previous PRs
Thank you!

**Comment by roxya** [comment]
Ok, set as default for new profiles/default button in the options page, and fixed the conflict.

**Review by andreakarasho — APPROVED** [review]

**Pull request merged**
