### PR TITLE
Save & Restore "scala"

### PR DESCRIPTION
**Pull request by plugtopus**
- Add to Debug Gump
- ScaleZoom to settings.json
- Save & Restore with relogin
- Move def value Apply() => Default()

3zjlvmd

### CODE REVIEW

**Comment by andreakarasho** [comment]
I haven't added it because in a lowend pc a low scale can decrease performance and cause app blocking.
A restart of ClassicUO can resolve the issue and the user will never set the scale anymore :D.

**Comment by plugtopus** [comment]
But this is solved by simply deleting the "Profiles" folder. I think  user himself is to blame if he sets a scale that his computer cannot process) On my server I play 0.9 to improve the FPS. My friend uses 1.2 constantly. I think the possibility of saving is a must.

I can add checkbox "reset the scale when entering the game" by default. It will be better this way?

**Comment by andreakarasho** [comment]
Yes add the checkbox please :)

**Comment by plugtopus** [comment]
3zk8mdz

**Pull request merged**
