### PR TITLE
Upgrade to dotnet style csproj

### PR DESCRIPTION
**Pull request by jaedan**
The project can now be built in a variety of ways.

Standard debug build: dotnet build
Standard release build: dotnet build -c release
Platform-specific, single file executable: dotnet publish -r <platform> -c
release

### CODE REVIEW

**Comment by andreakarasho** [comment]
From my knowledge a nercore environment  cannot load .net framework assembly.
This build will break razor and co.

**Comment by jaedan** [comment]
Yes it will. I can upgrade razor to .net core 3 too. I believe that can do winforms on Windows at least.

**Comment by Alias-Alan** [comment]
So will this still work with mac?

**Comment by andreakarasho** [comment]
done

**Pull request closed without merging**
