### PR TITLE
MP3Sharp as external submodule

### PR DESCRIPTION
**Pull request by ghost**
This will update MP3Sharp to it's newest version from the repository: https://github.com/ZaneDubya/MP3Sharp

Using a newer version will at least fix a bug with some music files not playing on loop (for example TheWanderer.mp3).

Music file that did not continue after loop ran into this error:
```
Error   | System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicUO.IO.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode(Int32 ch, Int32 gr)
   at ClassicUO.IO.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode()
   at ClassicUO.IO.Audio.MP3Sharp.Decoding.Decoder.DecodeFrame(Header header, Bitstream stream)
   at ClassicUO.IO.Audio.MP3Sharp.MP3Stream.ReadFrame()
   at ClassicUO.IO.Audio.MP3Sharp.MP3Stream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ClassicUO.IO.Audio.UOMusic.GetBuffer()
```

Same music file was tested after building with the newest MP3Sharp and the issue seems to be fixed.

There are also issues with music crackling sometimes, hopefully this might help with that too.

### CODE REVIEW

**Comment by andreakarasho** [comment]
> There are also issues with music crackling sometimes, hopefully this might help with that too.

It happens when you block the main thread like moving the window for more than 2/3s.

**Comment by andreakarasho** [comment]
It uses LGPL, im not sure it can work or linked with BSD-4.
I need to verify.

**Comment by ghost** [comment]
This is currently waiting if a PR (https://github.com/ZaneDubya/MP3Sharp/pull/13) can be merged to the MP3Sharp project to allow building against different frameworks and that way allow the build to succeed without having 4.0 framework version.

> It happens when you block the main thread like moving the window for more than 2/3s.

Will have to look at this separately, seems to be quite easily reproducible.

> It uses LGPL, im not sure it can work or linked with BSD-4.
I need to verify.

To my knowledge LGPL should be quite permissive. Github seems to nowadays provide a small TL;DR version of the license when you open for example https://github.com/ZaneDubya/MP3Sharp/blob/master/license.txt

**Comment by andreakarasho** [comment]
I didnot aware about that PR, cool!
Consider to reduce more the csproj contents and targeting netstandard2.0.
This is what i did for testing purposes:
https://github.com/andreakarasho/MP3Sharp/blob/master/MP3Sharp/MP3Sharp.csproj

**Comment by ghost** [comment]
I now created a new csproj file specifically targeting NET standard 2.0.

This seems to work and build okay for ubuntu. Something seems to be wrong with the macos build.

**Comment by ghost** [comment]
Could be that the macos build failing is unrelated to the changes in this PR.

It should also be noted that the MP3Sharp repository points to my fork at the moment, since it has not been merged into the original MP3Sharp repo.

**Comment by andreakarasho** [comment]
It's necessary to add the binary filename dll here:
https://github.com/andreakarasho/ClassicUO/blob/eb648b5397058dd3b752c69832d17c238416caba/tools/ManifestCreator/Program.cs#L15

**Comment by ghost** [comment]
Okay. I added the library into that list and ran the ManifestCreator. It produced this:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<releases>
	<release name="ClassicUO" version="1">
		<files>
			<file filename="ClassicUO.exe" hash="c1110384277d18019d4ca57d53afd5a0" />
			<file filename="cuoapi.dll" hash="2fbd9d072eefed8adc2f24e89ff71929" />
			<file filename="FNA.dll" hash="a6241dcd954b08638c503230ce86aeed" />
			<file filename="FNA.dll.config" hash="48854d13b3b3059ac0964381834d6fad" />
			<file filename="lib64/libFAudio.so.0" hash="da103febfb7de77791fe38e6d279bb40" />
			<file filename="lib64/libFNA3D.so.0" hash="51c26ed4623a3ef9e45b6294d99423ff" />
			<file filename="lib64/libSDL2-2.0.so.0" hash="ce6d3e695b37f93efa1705c71050c6c8" />
			<file filename="lib64/libtheorafile.so" hash="1b7d4283e78d25cb39cf5481b85f9280" />
			<file filename="osx/libFAudio.0.dylib" hash="59d26be01e34e48c17771d4ce5edc73a" />
			<file filename="osx/libFNA3D.0.dylib" hash="d403e637f8b9025784e0d29c9e3c844b" />
			<file filename="osx/libSDL2-2.0.0.dylib" hash="85a6c89662a49999943d5fc0b79191f9" />
			<file filename="osx/libtheorafile.dylib" hash="bd26f2ded089558f7edf626e63b95e3e" />
			<file filename="osx/libMoltenVK.dylib" hash="ee50885c995cbd6ab4a2609f77a81875" />
			<file filename="osx/libvulkan.1.dylib" hash="043ffd3789c5f3dab8dac629044fa886" />
			<file filename="vulkan/icd.d/MoltenVK_icd.json" hash="aec5425c754c2155c783383be7fe8e4b" />
			<file filename="x64/FAudio.dll" hash="c697faf8a3d467e64cca6e5b38890a82" />
			<file filename="x64/FNA3D.dll" hash="58f05d1a079c499206b00336ff557c50" />
			<file filename="x64/SDL2.dll" hash="f9a859a7690fc35c5a925739ebe65fa2" />
			<file filename="x64/zlib.dll" hash="12180b59e1828516e42f801d25e48968" />
			<file filename="x64/libtheorafile.dll" hash="953688b059b268aa38ef7fbc3032cbc1" />
			<file filename="x64/vcruntime140.dll" hash="971dbbe854fc6ab78c095607dfad7b5c" />
			<file filename="MP3Sharp.dll" hash="34e6c456ab9afe7c49ba9d22182c8994" />
		</files>
	</release>
</releases>
```

**Pull request merged**
