### PR TITLE
StatusGump (Text from Clilocs)

### PR DESCRIPTION
**Pull request by tonyuo**

### CODE REVIEW

**Comment by tonyuo** [comment]
An S missing at first 5

**Comment by gaechti** [comment]
you need to point your PRs to dev branch, not master branch

**Comment by tonyuo** [comment]
> you need to point your PRs to dev branch, not master branch

Don't know what you mean. I'm new at Github

**Comment by gaechti** [comment]
> 

Karasho fixed it for you :)
grafik

**Pull request merged**
