### PR TITLE
GetTexture ContainsKey g fix

### LINKED ISSUE #303: Elf (7.0.18)
### CUO

404kxdm

404kzkl

### 7.0.18 (all ok)

404kgs0

### PR DESCRIPTION
**Pull request by zolter**
#303

### CODE REVIEW

**Comment by andreakarasho** [comment]
the `TryGetValue(g, out SpriteTexture texture)` already check if value exists

**Comment by zolter** [comment]
No :)

**Comment by zolter** [comment]
a2

a1

end..... HELLO 5593 :)

a3

**Comment by andreakarasho** [comment]
Yes. Internally it check if key exists, if it exists return true and the SPriteTexture.
I think the problem is the second check: || texture.IsDisposed, because it means that i already exists into dictionary and when it does dictionary.Add it throws an exception.
There is a problem with that texture, it is disposed manyally somewhere around the code

**Comment by zolter** [comment]
Yep, without ` || texture.IsDisposed` all work fine

**Comment by andreakarasho** [comment]
Ok. Im seeing that 5593 is related to mapinfo when you chose the map.
Im investigating..

**Comment by andreakarasho** [comment]
```csharp
if (mapInfo.Index == 0 || mapInfo.Index == 3)
          {
              var texture = FileManager.Gumps.GetTexture(mapInfo.Gump);
              if (texture == null)
              {
                  SkipSection = true;
                  return;
              }
              else
                  texture.Dispose(); // TOTALLY WRONG!!!!!!!
          }
```

**Comment by andreakarasho** [comment]
Try it now with latest commint please

**Comment by zolter** [comment]
Yep, brakepoint stop in this line

**Pull request closed without merging**
