### PR TITLE
Summon timer

### PR DESCRIPTION
**Pull request by gaechti**
This will add an option to show the summon timer after the HP in the overhead.

Color will change to yellow at 60 sec, orange at 40 sec, red at 20sec

Right now its tied to HP and on all summons.
This could be changed to stay on your own summon "permanently", but I would love some community feedback here what options would make sense

### CODE REVIEW

**Comment by gaechti** [comment]
I see PRs unanswered for weeks/ a month plus while others get merged in less than an hour. It seems obvious that qol features like this are not considered right now. Should this change, DM me and I reopen

**Comment by Alias-Alan** [comment]
Appropriate move. An opensource commmunity project with multiple pr's being ignored while a specific group of two push pr's that get reviewed, approved, while multiple pr's touch on whats-missing and fixes the same exact issues but are ignored for months while the issue persist to continue. Ultimately it's Karasho's project, all you can do is identify the problem, resolve them, and hope they manage to figure out how to solve them.
I have faith that karasho can get it done.

**Comment by andreakarasho** [comment]
All PR's i merged, except 1 or 2, in the last month are bug fixing and code improvement or at least they don't affect the gameplay deeply [like the first PR you did @gaechti ] or the customization level is quite low.

You should consider the fact that this client aims to support all UO version.
Making something like this PR could affect various aspects of the game that now we don't know or we didn't think about. 
Example: i did the grid containers, but i didn't think about the importance of hide objects into the backpack. This fact will make life easier for ingame robbers. Infact this branch is not merged atm.

Another aspect i'd like to explain is: most of the PR i instant accepted contain lot of code issues and bad pratices. I can't spend my time to make them workable. 
Example: @roxya [he's the first guy I ever thought of] writes good code imho and he has really good ideas, for me this guy can be consider a Developer and not a Contributor. [I still don't know why he didn't join the CUO team.]

Do you want make valid PR for CUO?
- avoid high customization [like cut string, takes server messages, buffers]
- avoid cheating stuff like mark obastcles or impassable tiles
- write good code

@Syrupz-UO What do you mean with "Ultimately it's Karasho's project" ? Who is the owner :D ? You? 
And can you give me an example of this "while multiple pr's touch on whats-missing and fixes the same exact issues but are ignored for months while the issue persist to continue."?

Thank you!

**Comment by gaechti** [comment]
Karasho, first let me tell you, I really have mad respect of you. What you done here, built a client from ground up, the time investment, kudos. 

I totaly get the client is to aim for all shards. But this should not be an argument. This should be an incentive on how to make it happend..
I also wrote in the last edit to add uoguide.com calcs for the timer could be used on non outlands shards (or shards that dont supply the time).
Just a few hours after the PR, I had already three PMs if the same could be done for peacemaking. I looked into it, can be done. Same method. I didnt make a PR for that as I wanted to see if this one goes anywhere.

I understand, my code is not the best. I havent done any c# before (or anything really bejond some easy php). If you tell me, code is bad, idea is good. Totaly fine. I dont ask you to teach me.

But you cant say the same for e.g.: Hezkores Bandies Gump or the PRs that just add a macro..


I really wanted to help you with this great client. Show some ideas, try em out with my limited coding skills, and share it.. Dont say talk about em first. Sometimes you just need to do it to even see how big the benefit is. And I dont mean cheaty stuff.

Imho its small features like theese that make a client great. Features that makes ppls lives easyer. All this will move even more players to use your client..

**Comment by Alias-Alan** [comment]
Gaechti made an astounding comment, I support everything he mentions. You're not a dolt, you're quite brilliant  but when you respond with messges like this:

Syrupz-UO What do you mean with "Ultimately it's Karasho's project" ? Who is the owner :D ? You?

How can thr community not look at you foolishly? I guess by me saying it's your project, that SOME HOW might lead you to believe I am unaware of who created this project... that SOME HOW it transcends your comprehension which I highly doubt as you speak English very well for it not being your native language. However, you ask if I am the owner after I clearly state the project is yours. I don't really know how to respond to this, perhaps you didn't quite think that comment out? 

Your next comment/question to me is even worse than the first. So, I'll assume it's an innocent attempt at trolling.

**Pull request closed without merging**
