### PR TITLE
Fix login music playing in gamescene

### PR DESCRIPTION
**Pull request by ghost**
Issue:

- If the server does not send PlayMusic on login (Outlands), the login music stays in the "normal" music index.
- Season change starts playing the season music, but this is loaded into the "war" music index.
- Switching between war mode and peace mode will result in login music being played in the game scene.

This would be fixed by loading the season music into the "normal" music index and playing it over login music.

### CODE REVIEW

**Comment by andreakarasho** [comment]
Can’t merge due to conflicts.
Make a clean PR please

**Comment by ghost** [comment]
```
$ git merge classicuo/dev
Already up to date.
```

Does the conflict refer to the build checks? I now have two pull requests that fail to macos build. Seems that my changes should not affect the build but can't be sure.

**Comment by andreakarasho** [comment]
image

if you look at the commits history above you see commits of mine in your PR too

**Comment by ghost** [comment]
Okay, I might have messed this up since I started the branch from master instead of dev. I will recreate this PR.

**Pull request closed without merging**
