### PR TITLE
HBG (Updated all files)

### PR DESCRIPTION
**Pull request by Alias-Alan**
CustomHealthBars
Still no idea on commit history

### CODE REVIEW

**Comment by roxya** [comment]
You are missing CustomBarsToggled in the profile, so it will not build.

**Comment by roxya** [comment]
If I pull healthbars from the NameOverheadGump, it is always the old style

**Comment by roxya** [comment]
If I switch to the large status bar and back to a small one, my healthbar becomes the old style one

**Comment by roxya** [comment]
It's supposed to use the gump graphics for bars? Looks like a strange mix of old and new
image

**Comment by Alias-Alan** [comment]
That does look strange
image

**Comment by Alias-Alan** [comment]
I've added checks to every file that generates a healthgumpbar -the ones I missed were 
[
packethandlers.cs
partymanager.cs
partygumpadvanced.cs
statusgump.cs
nameoverheadgump.cs
paperdollgump.cs
]
All of which have been added and throw no exceptions, fixes the paperdoll gump produced, minimizing and maximizing is fixed, name over head is fixed, as well as party handling.

**Comment by Alias-Alan** [comment]
Fixing party issue

**Pull request closed without merging**
