### PR TITLE
Fix ReadASCII/WriteASCII using ASCII instead of cp-1252

### PR DESCRIPTION
**Pull request by brndd**
Reopening #1425 because this is still an issue. There was apparently something wrong with this PR, but I do not know what because I have been playing with this fix for the past month and have had no issues. Double-check that the new NuGet dependency is added and loaded correctly before merging.

### CODE REVIEW

**Comment by andreakarasho** [comment]
Does the `System.Text.Encoding.CodePages` add a new dll?
If it does, we need to add the module name to `/tools/ManifestCreator.csproj`

**Comment by brndd** [comment]
Yeah it does, `System.Text.Encoding.CodePages.dll`. Perhaps that's the issue; I've added it there now.

**Comment by andreakarasho** [comment]
In the past I read somewhere that calling `Encoing.GetEncoding` may be very unperformant.
It's better to use a `static` var i guess.

**Comment by brndd** [comment]
I moved this to StringHelper, which handles the RegisterProvider call and caches the encoding so we don't do `GetEncoding()` calls every time.

**Pull request merged**
