### PR TITLE
Marking cave tiles

### PR DESCRIPTION
**Pull request by zolter**
clip2net_190204221754

### CODE REVIEW

**Comment by andreakarasho** [comment]
you need to update your branch

**Comment by zolter** [comment]
Ok i'll take a look in the evening

**Comment by zolter** [comment]
Try it now, if don’t work, I’ll do create clean PR in the evening.

**Comment by andreakarasho** [comment]
cannot do that :D 
```### This branch cannot be rebased due to conflicts````

**Comment by zolter** [comment]
I will check it from my home computer)

**Pull request closed without merging**
