### PR TITLE
they are just .so on linux

### PR DESCRIPTION
**Pull request by DarkLotus**

### CODE REVIEW

**Comment by andreakarasho** [comment]
I looked at fna src code:
https://github.com/FNA-XNA/FNA/blob/master/FNA.dll.config

Do you receive errors with current settings?

**Comment by DarkLotus** [comment]
https://github.com/andreakarasho/ClassicUO/tree/master/src/libs/lib If you look in our libs folder ours are named just .so not .so.0

with .so.0 Client crashes with no audio device found because the library is missing.

**Comment by andreakarasho** [comment]
That's weird. Im totally agree with you, but all fna game should throw this exception.
Anyway i think you found the issue with mac also. Before merge, can you fix the whole file with the right libraries name?

**Comment by DarkLotus** [comment]
The rest look okay on my end.

**Pull request merged**
