### PR TITLE
Minimum drag distance

### PR DESCRIPTION
**Pull request by jkachhad**
Requires a minimum distance that the mouse move to consider a drag. Resolves an issue where players may be clicking rapidly (mount/dismount), and a single pixel move during LButton Down could be considered a drag.

Currently set to 3 pixels.

### CODE REVIEW

**Comment by jkachhad** [comment]
A discussion point prior to merge: why was DragBegin raised AFTER MouseDrag? Shouldn't it be raised prior to any dragging logic? I've changed it to this behavior in this commit and did not notice any input issues.

**Review by SaschaKP — CHANGES_REQUESTED** [review]
please, whenever you want to do patches or submit modifications, at the moment you should refer to the "dev" branch.

Master is used only for official submissions, the dev branch is ATM the active development branch with the latest modifications inside.

**Comment by jkachhad** [comment]
Rebased into ```andreakarasho:dev``` branch as requested.

**Review by SaschaKP — APPROVED** [review]
tested

**Pull request merged**
