### PR TITLE
drag select humanoids only option

### PR DESCRIPTION
**Pull request by roxya**
This disappeared when I accidentally deleted the branch while "cleaning" my github! But good chance to rebase and remove any conflicts that appeared along the way.

(pvp players asked for this feature)

### CODE REVIEW

**Comment by andreakarasho** [comment]
I'm not sure about it.
Seems like a limitation in different context.
For example: if you have to drag an heal potion from the ground to survive, with this option ON you will die.

**Comment by roxya** [comment]
It doesn't drag if you mouse down on an unlocked Item

https://github.com/andreakarasho/ClassicUO/blob/045b2bbceeaa7152fbc8633a0280049c822752fd/src/Game/Scenes/GameSceneInputHandler.cs#L124-L127

And this pr just adds a filter to what mobiles are included in the already existing function

**Comment by andreakarasho** [comment]
Exactly if you cannot drag the potion (for example) your gameplay is really limited.
It's dangerous. Any workaround ?

**Comment by andreakarasho** [comment]
Ok. It has been a misanderstand. This PR is referred to the DragSelection feature.

Can you solve conflicts?

**Comment by roxya** [comment]
Done :)

**Pull request merged**
