### PR TITLE
Multiple feature changes (tree to stump / blockers / energy bolt / highlight tiles)

### PR DESCRIPTION
**Pull request by gaechti**
-Tree to Stump: Changed to stump or tile, tile colorable
-Blockers: Added blockers, to stump/rock or tile, tile colorable
-Tiles at range highlightable
-Colorable energy bolt

### CODE REVIEW

**Comment by gaechti** [comment]
Sorry, looks like I had older version of GameSceneDrawingSorting.cs, I will update

**Comment by gaechti** [comment]
looks good to me now

**Comment by andreakarasho** [comment]
I'll evaluate this PR after the 1.2.1 BETA release because i'm planning some cool stuff about customization of CUO, but it needs time and at the moment it's only a vague idea.
IMHO this PR remains valid 

Thank you for your patience :)

**Comment by gaechti** [comment]
Thanks for the reply
Theres a bug right now with the "if (!itemData.IsImpassable) continue;" if you change the type a few times all trees go poof..
I will look into it once I finished helping Alan with custom healthbars
Also update the conflicting files

Should I close this pr and resubmit or keep it open?

**Comment by Stallind** [comment]
@gaechti rebase on dev so it can merge and it should be fine

**Comment by gaechti** [comment]
the bug is fixed and files should be good BUT

dunno if I did something wrong... (git noob)
Resolved the conflicts in webbrowser and now it says
"This branch cannot be rebased due to conflicts"

@andreakarasho 
if it cannot be merged I close this PR and re-open it

**Comment by gaechti** [comment]
I redo this, sorry something went wront on my side

**Pull request closed without merging**
