### PR TITLE
Click to spell name bug

### LINKED ISSUE #306: Click to spell name bug
1. Click "Strength" spell name -> open "Cure" (https://i.imgur.com/YV5giiR.gif)

2. Click  "Lighting" -> open "Fire field" (https://i.imgur.com/3EYWW9M.gif) 

The problem is reproduced with all the "latest" spells on the list.

7.0.18

### PR DESCRIPTION
**Pull request by jkachhad**
Fix where spell numbers were off by 1 page, may need testing from @zolter 
Closes #306 .

### CODE REVIEW

**Comment by andreakarasho** [comment]
Does it work with a non fully spellbook?

**Comment by zolter** [comment]
I think it work fine (with non full spellbook too)
But need use dev branch @jkachhad

**Comment by jkachhad** [comment]
Rebased to ```dev```

**Comment by zolter** [comment]
**Without fix**
(def client + def 56d)
https://i.imgur.com/4jRUKdq.gif

**With fix**
https://i.imgur.com/jRtxjJr.gif
and full spellbook
https://i.imgur.com/exMFG5C.gif

I think it work for me 👍

**Pull request merged**
