### PR TITLE
Login Scane (login&passwd field focus), TextBox SetNextFocus

### PR DESCRIPTION
**Pull request by plugtopus**
**SetNextFocus** method to set next TextBox focus elem

3zfwfir

### CODE REVIEW

**Review by andreakarasho — COMMENTED** [review]
I think that is not the best and beautiful way to do it.
You should use parent.findcontrol<T>() and search for another control that accepts the input keyboard, then set focus to it

**Comment by plugtopus** [comment]
I thought so too, but I decided that for the two fields it would be too complicated code. 
Ok, I'll fix it soon.

**Comment by plugtopus** [comment]
I created **NextElement()** to search for the next TextBox item. 

> case SDL.SDL_Keycode.SDLK_TAB:
> NextElement().SetKeyboardFocus();
> break;

**Comment by andreakarasho** [comment]
Trust me : 
https://github.com/3HMonkey/JuicyUO/blob/e9f26d450598ee080af98dc2ceff9be574ce4a94/JuicyUO/Core/UI/AControl.cs#L874

**Comment by plugtopus** [comment]
Make a similar implementation or you duplicate it yourself?

**Comment by andreakarasho** [comment]
similar implementation !
Thanks for your work :)

**Comment by plugtopus** [comment]
Np :)

**Comment by andreakarasho** [comment]
how is going on?

**Comment by plugtopus** [comment]
Temporarily switched to another task, there is absolutely no time to return.
I can close "Pull request" and transfer to "Issues".

**Comment by andreakarasho** [comment]
ok i do it :)

**Pull request closed without merging**
