### PR TITLE
Disable default UO hotkeys + New Macro "MovePlayer"

### PR DESCRIPTION
**Pull request by zolter**
41MbdE5
3dd4f-clip-126kb

Disable default UO hotkeys
- Disable arrows & numlock arrows (player moving)
- Disable TAB (toggle warmode)
- Disable Ctrl + Q/W (messageHistory)

New Macro "MovePlayer": 
- Top, Right, Down, Left

New macro: 
- Aura - hold to draw aura, 
- AuraOnOff - toggle aura visibility

_Multiple button support (top+left etc) but works only 1 "MovePlayer" for one macro button._

### CODE REVIEW

**Comment by zolter** [comment]
#441 + I remember request for non-standard player movement buttons
I think we should develop it further to improve flexibility.

**Comment by roxya** [comment]
Tried out your WASD movement, love it. Feels like a different game almost!

**Comment by andreakarasho** [comment]
In these days i ll put an eye. Thanks!

**Comment by andreakarasho** [comment]
resolve conflicts dude

**Pull request closed without merging**
