### PR TITLE
Add some basic Mobile unit tests

### PR DESCRIPTION
**Pull request by mchekin**
Adding some basic Mobile unit tests.

### CODE REVIEW

**Comment by andreakarasho** [comment]
thank you!
just point to 'dev' branch instead of master

**Comment by mchekin** [comment]
@andreakarasho 

Thank you!
Done.

**Comment by andreakarasho** [comment]
solve conflicts please

**Comment by mchekin** [comment]
@andreakarasho 

Something went wrong with this pull request (I don't see any conflicts locally and I have some commits that don't belong to the pull-request)

I close this one and opened a new clean one instead:
https://github.com/andreakarasho/ClassicUO/pull/1333

Thank you.
And sorry for the mess :)

**Pull request closed without merging**
